### PR TITLE
Separate on-dhcp-proxy to be loosely-coupled with RackHD

### PR DESCRIPTION
**Pull request by anhou**
PR for proposal PR for proposal https://groups.google.com/forum/#!topic/rackhd/I81Tl2qkQMI
requires PR https://github.com/RackHD/on-http/pull/411

maybe 'simplify on-dhcp-proxy' is more accurate. most duplicated code logic is removed. Removed code logic have been implemented in southbound API GET /profiles route

@RackHD/corecommitters  @benno  @jlongever

### CODE REVIEW

**Comment by benbp** [comment]
Should probably say this requires https://github.com/RackHD/on-http/pull/411 (tests won't pass if merged separately I think).

👍

**Comment by anhou** [comment]
test this please

**Comment by anhou** [comment]
@benbp actually, Jenkins has passed :),  that's why most code logic are duplicated,  it could works without most of codes here. although need enhancement in on-http :)

**Comment by brianparry** [comment]
@anhou @benbp Given these changes, is there any reason to continue using a DHCP proxy at all?

**Comment by anhou** [comment]
@brianparry Temporally,  the only reason is it's like a plugin to avoid config isc-dhcp-server 's dhcpd.conf, and also isc-dhcp-poller also exist in on-dhcp-proxy(default is disabled).  and a small side functionality is that the log we could control is at independent on-dhcp-proxy.log instead of isc-dhcp-server's logs in /var/log/syslog.  Overall, I think on-dhcp-proxy could be deprecated finally after dhcpd.conf configuration  fully replace getDefaultBootfile's functionally, it's a gradually process for migration.  of course, if it's harmless, we could leave it there.  @RackHD/corecommitters  for awareness.

**Comment by yyscamper** [comment]
:+1:

**Comment by anhou** [comment]
test this please

**Pull request merged**
