### PR TITLE
Replace reference to common API with current

### PR DESCRIPTION
**Pull request by brianparry**
@RackHD/corecommitters @keedya @dalebremner @BillyAbildgaard

### CODE REVIEW

**Comment by keedya** [comment]
:+1:

**Comment by brianparry** [comment]
test this please

**Comment by benbp** [comment]
👍

**Comment by yyscamper** [comment]
:+1:

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by brianparry** [comment]
failing tests should be fixed now.

**Pull request merged**
