### PR TITLE
Better init script

### PR DESCRIPTION
**Pull request by ytjohn**
- enable start/stop/restart and pid monitoring
 - put logs in /var/log/rackhd

https://github.com/RackHD/on-http/issues/416

### CODE REVIEW

**Comment by ytjohn** [comment]
Hold up on this - still has issues relating to background task. Might implement start-stop-daemon.

**Comment by ytjohn** [comment]
Upgraded script to use start-stop-daemon.

**Comment by yyscamper** [comment]
@ytjohn : whether the issue you mentioned has been resolved in the latest code?

**Comment by ytjohn** [comment]
@yyscamper No, it won't be resolved until the init scripts are merged in. The current set of init scripts (that replaced upstart configs) merely run the daemon in the background and will close out when the shell is exited. 

We are manually injecting the PR'd init scripts in our environment before the packages are installed.

**Comment by ytjohn** [comment]
@yyscamper   Might have misunderstood your question. The background task I mentioned in this PR is resolved with my latest commit.

**Comment by ytjohn** [comment]
code is ready for merge following e95b1ba

**Comment by ytjohn** [comment]
I did a bit more looking, and I realized I should add exit levels.  Let me push up a commit that includes those.

https://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/iniscrptact.html

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
retest this please

**Comment by changev** [comment]
test this please

**Comment by jimturnquist** [comment]
What is left for this to be merged?

**Comment by ytjohn** [comment]
All changes are pushed. Let me know if there's anything else preventing these from being merged in.

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by ytjohn** [comment]
Added error message suggested by @davidzuhn 

```
root@rackhd01:~# /etc/init.d/on-taskgraph start
Service disabled due to absence of /etc/default/on-taskgraph
root@rackhd01:~# touch /etc/default/on-taskgraph
root@rackhd01:~# /etc/init.d/on-taskgraph start
on-taskgraph already running with pid 30132
```

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by jimturnquist** [comment]
Can we get this one merged? Is there anything left that is needed?

**Comment by yyscamper** [comment]
:+1:

**Comment by anhou** [comment]
:+1:

**Pull request merged**
